package com.fly.crm_bos;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crm.fly.com/")
@XmlSeeAlso({
   // ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.fly.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedIdByAddress", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindDecidedIdByAddress")
    @ResponseWrapper(localName = "findDecidedIdByAddressResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindDecidedIdByAddressResponse")
    public String findDecidedIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.fly.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListNotAssociate", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindListNotAssociate")
    @ResponseWrapper(localName = "findListNotAssociateResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindListNotAssociateResponse")
    public List<Customer> findListNotAssociate();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.fly.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListAssociated", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindListAssociated")
    @ResponseWrapper(localName = "findListAssociatedResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindListAssociatedResponse")
    public List<Customer> findListAssociated(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.fly.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomer", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.AssignCustomer")
    @ResponseWrapper(localName = "assignCustomerResponse", targetNamespace = "http://service.crm.fly.com/", className = "com.fly.crm.service.AssignCustomerResponse")
    public void assignCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

}
